// This file is generated by Fatima.

function requireString(value, key) { if (typeof value !== "string") throw new Error(`Missing environment variable: ${key}`); return value; }
function string(value, key) { return requireString(value, key); }
function nonEmpty(value, key) { const v = requireString(value, key); if (v.trim().length === 0) throw new Error(`Expected a non-empty value for ${key}`); return v; }
function email(value, key) { const v = requireString(value, key); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)) throw new Error(`Expected a valid email for ${key}`); return v; }
function url(value, key) { const v = requireString(value, key); try { new URL(v); } catch { throw new Error(`Expected a valid URL for ${key}`); } return v; }
function uuid(value, key) { const v = requireString(value, key); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{12}$/i.test(v)) throw new Error(`Expected a valid UUID for ${key}`); return v; }
function number(value, key) { const v = Number(requireString(value, key)); if (Number.isNaN(v)) throw new Error(`Expected a number for ${key}`); return v; }
function integer(value, key) { const v = number(value, key); if (!Number.isInteger(v)) throw new Error(`Expected an integer for ${key}`); return v; }
function boolean(value, key) { const v = requireString(value, key).toLowerCase(); if (["true","1","yes","on","y","enabled"].includes(v)) return true; if (["false","0","no","off","n","disabled"].includes(v)) return false; throw new Error(`Expected a boolean for ${key}`); }
function json(value, key) { try { return JSON.parse(requireString(value, key)); } catch { throw new Error(`Expected valid JSON for ${key}`); } }
function oneOf(value, key, values) { if (!values.includes(value)) throw new Error(`Expected one of ${values.join(", ")} for ${key}`); return value; }
function pem(value, key) { const v = requireString(value, key); if (!/-----BEGIN [A-Z0-9 ]+-----[\s\S]+-----END [A-Z0-9 ]+-----/.test(v)) throw new Error(`Expected a valid PEM value for ${key}`); return v; }
function secretKey(value, key) { const v = requireString(value, key); if (!/^sk[-_][A-Za-z0-9._-]+$/.test(v)) throw new Error(`Expected a valid sk secret for ${key}`); return v; }
function bearer(value, key) { const v = requireString(value, key); if (!/^Bearer\s+.+$/.test(v)) throw new Error(`Expected a valid bearer token for ${key}`); return v; }

// __FATIMA_REGISTER__

let __CACHE_NAME__;

function __RESOLVE_NAME__() {
	__CACHE_NAME__ ??= Object.freeze({
		// __OBJECT_BODY__
	});
	return __CACHE_NAME__;
}

const __EXPORT_NAME__ = Object.freeze({
	// __GETTER_BODY__
});

// __FATIMA_EXPORTS__
