// This file is generated by Fatima.
// __FATIMA_IMPORTS__

type Prettify<T> = {
	[K in keyof T]: T[K];
} & {};

type AnyValue = unknown;

function requireString(value: unknown, key: string): string { if (typeof value !== "string") throw new Error(`Missing environment variable: ${key}`); return value; }
function string(value: unknown, key: string): string { return requireString(value, key); }
function nonEmpty(value: unknown, key: string): string { const v = requireString(value, key); if (v.trim().length === 0) throw new Error(`Expected a non-empty value for ${key}`); return v; }
function email(value: unknown, key: string): string { const v = requireString(value, key); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)) throw new Error(`Expected a valid email for ${key}`); return v; }
function url(value: unknown, key: string): string { const v = requireString(value, key); try { new URL(v); } catch { throw new Error(`Expected a valid URL for ${key}`); } return v; }
function uuid(value: unknown, key: string): string { const v = requireString(value, key); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{12}$/i.test(v)) throw new Error(`Expected a valid UUID for ${key}`); return v; }
function number(value: unknown, key: string): number { const v = Number(requireString(value, key)); if (Number.isNaN(v)) throw new Error(`Expected a number for ${key}`); return v; }
function integer(value: unknown, key: string): number { const v = number(value, key); if (!Number.isInteger(v)) throw new Error(`Expected an integer for ${key}`); return v; }
function boolean(value: unknown, key: string): boolean { const v = requireString(value, key).toLowerCase(); if (["true","1","yes","on","y","enabled"].includes(v)) return true; if (["false","0","no","off","n","disabled"].includes(v)) return false; throw new Error(`Expected a boolean for ${key}`); }
function json(value: unknown, key: string): unknown { try { return JSON.parse(requireString(value, key)); } catch { throw new Error(`Expected valid JSON for ${key}`); } }
function oneOf<T>(value: T, key: string, values: T[]): T { if (!values.includes(value)) throw new Error(`Expected one of ${values.join(", ")} for ${key}`); return value; }
function pem(value: unknown, key: string): string { const v = requireString(value, key); if (!/-----BEGIN [A-Z0-9 ]+-----[\s\S]+-----END [A-Z0-9 ]+-----/.test(v)) throw new Error(`Expected a valid PEM value for ${key}`); return v; }
function secretKey(value: unknown, key: string): string { const v = requireString(value, key); if (!/^sk[-_][A-Za-z0-9._-]+$/.test(v)) throw new Error(`Expected a valid sk secret for ${key}`); return v; }
function bearer(value: unknown, key: string): string { const v = requireString(value, key); if (!/^Bearer\s+.+$/.test(v)) throw new Error(`Expected a valid bearer token for ${key}`); return v; }

// __FATIMA_REGISTER__

type EnvObject = Prettify<{
	// __TYPE_BODY__
}>;

export type CreatePrivateEnv<Keys extends PropertyKey, Prefix extends string> = {
	[K in Keys as K extends `${Prefix}${string}` ? never : K]: K extends keyof EnvObject ? EnvObject[K] : never;
};

export type CreatePublicEnv<Keys extends PropertyKey, Prefix extends string> = {
	[K in Keys as K extends `${Prefix}${string}` ? K : never]: K extends keyof EnvObject ? EnvObject[K] : never;
};

export type EnvKeys = keyof EnvObject;
export type Env = Prettify<CreatePrivateEnv<EnvKeys, "__PUBLIC_PREFIX__">>;
export type PublicEnv = Prettify<CreatePublicEnv<EnvKeys, "__PUBLIC_PREFIX__">>;

type EnvResolvers<T extends Record<string, AnyValue>> = {
	[K in keyof T]: () => T[K];
};

function createEnv<T extends Record<string, AnyValue>>(resolvers: EnvResolvers<T>, options: { isServer?: () => boolean } = {}): T {
	const isServer = options.isServer ?? (() => typeof window === "undefined");

	function forbidden(key: string): never {
		throw new Error([
			`Environment variable ${key} not allowed on the client.`,
			"Here are some possible fixes:",
			"\n 1. Add the public prefix to your variable if you want to expose it to the client.",
			"\n 2. Check if your public prefix is correct by assigning 'public-prefix' to your Fatima configuration.",
		].join("\n"));
	}

	return new Proxy(resolvers, {
		get(target, key) {
			if (typeof key !== "string" || key === "__esModule" || key === "$$typeof") return undefined;
			if (!isServer()) forbidden(key);
			const resolve = Reflect.get(target, key);
			return typeof resolve === "function" ? resolve() : undefined;
		},
	}) as T;
}

const env = createEnv<Env>({
	// __PRIVATE_RESOLVERS__
});

export { env };
