// This file is generated by Fatima.

type Prettify<T> = {
	[K in keyof T]: T[K];
} & {};

type PublicEnv = Prettify<{
	// __TYPE_BODY__
}>;

function createPublicEnv<T extends Record<string, unknown>>(values: T): Readonly<T> {
	return Object.freeze(values);
}

const publicEnv = createPublicEnv<PublicEnv>({
	// __PUBLIC_VALUES__
});

export { publicEnv };
export type { PublicEnv };
