import type { FatimaGenerator } from "../plugins/types";

function toPythonIdentifier(key: string) {
	const sanitized = key.replaceAll(/[^A-Za-z0-9_]/g, "_");
	const normalized = /^[A-Za-z_]/.test(sanitized) ? sanitized : `_${sanitized}`;
	return normalized || "_ENV";
}

function resolvePythonType(model: unknown) {
	const modelName =
		typeof model === "string"
			? model
			: model &&
					typeof model === "object" &&
					typeof (model as { type?: unknown }).type === "string"
				? (model as { type: string }).type
				: undefined;

	switch (modelName) {
		case "number":
		case "integer":
			return "float";
		case "boolean":
			return "bool";
		case "json":
			return "object";
		default:
			return "str";
	}
}

export const pythonGenerator: FatimaGenerator = {
	async generate(context) {
		const keys = Object.keys(context.loadedEnv);
		const content = [
			"# This file is generated by Fatima.",
			"import json",
			"import os",
			"from typing import TypedDict",
			"",
			"class Env(TypedDict):",
			...keys.map(
				(key) =>
					`    ${toPythonIdentifier(key)}: ${resolvePythonType(context.model?.[key])}`,
			),
			"",
			"env: Env = {",
			...keys.map(
				(key) =>
					`    ${JSON.stringify(key)}: os.environ[${JSON.stringify(key)}],`,
			),
			"}",
		].join("\n");

		return [{ path: context.file, content }];
	},
};
