import { format } from "../lib/format";
import type { FatimaGenerator } from "../plugins/types";
import {
	getPublicKeys,
	getSiblingPublicPath,
	renderBuiltinHelpers,
	resolveModelSpecs,
} from "./shared";

function renderTypescriptFile(params: {
	name: string;
	context: Parameters<typeof resolveModelSpecs>[0];
	keys: string[];
	filePath: string;
}) {
	const specs = resolveModelSpecs(params.context, params.keys, {
		rawValueExpression: (key) => `process.env[${JSON.stringify(key)}]!`,
		defaultType: "string",
	});
	const imports = Array.from(new Set(specs.flatMap((item) => item.imports)));
	const typeName = params.name === "env" ? "Env" : "PublicEnv";
	const exportName = params.name === "env" ? "env" : "publicEnv";

	return format(
		[
			"// This file is generated by Fatima.",
			imports.length ? imports.join("\n") : "",
			imports.length ? "" : "",
			renderBuiltinHelpers("typescript"),
			"",
			`export type ${typeName} = {${specs.map((item) => `\n\t${JSON.stringify(item.key)}: ${item.type};`).join("")}\n};`,
			"",
			`export const ${exportName} = Object.freeze({`,
			...specs.map(
				(item) => `\t${JSON.stringify(item.key)}: ${item.expression},`,
			),
			`}) as ${typeName};`,
		]
			.filter(Boolean)
			.join("\n"),
		{
			cwd: params.context.cwd,
			filePath: params.filePath,
			formatter: params.context.formatter,
		},
	);
}

export const typescriptGenerator: FatimaGenerator = {
	async generate(context) {
		const keys = Object.keys(context.loadedEnv);
		const publicKeys = getPublicKeys(keys, context.publicPrefix ?? "PUBLIC_");

		const envContent = await renderTypescriptFile({
			name: "env",
			context,
			keys,
			filePath: context.file,
		});
		const publicPath = getSiblingPublicPath(context.file);
		const publicContent = await renderTypescriptFile({
			name: "publicEnv",
			context,
			keys: publicKeys,
			filePath: publicPath,
		});

		return [
			{ path: context.file, content: envContent },
			{ path: publicPath, content: publicContent },
		];
	},
};
